<a href="https://colab.research.google.com/github/jaison-03/23_9_26_git/blob/main/NLP_Text_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gensim scikit-learn pandas numpy

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.1)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 62.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [2]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

from gensim.models import Word2Vec
from gensim.models import FastText

In [3]:
documents = [
    "I love Python programming",
    "Python is easy to learn",
    "I love learning NLP",
    "NLP is interesting and useful"
]

print(documents)

['I love Python programming', 'Python is easy to learn', 'I love learning NLP', 'NLP is interesting and useful']

In [4]:
for i, document in enumerate(documents):
    print("Document", i + 1, ":", document)

Document 1 : I love Python programming
Document 2 : Python is easy to learn
Document 3 : I love learning NLP
Document 4 : NLP is interesting and useful

In [5]:
enumerate(documents)

In [7]:
vectorizer = CountVectorizer()
vectorizer

CountVectorizer()

In [10]:
bow_matrix = vectorizer.fit_transform(documents)
bow_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 16 stored elements and shape (4, 12)>

In [11]:
vocabulary = vectorizer.get_feature_names_out()

print(vocabulary)

['and' 'easy' 'interesting' 'is' 'learn' 'learning' 'love' 'nlp'
 'programming' 'python' 'to' 'useful']

In [12]:
print(bow_matrix.toarray())

[[0 0 0 0 0 0 1 0 1 1 0 0]
 [0 1 0 1 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0]
 [1 0 1 1 0 0 0 1 0 0 0 1]]

In [13]:
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vocabulary
)

bow_df

,and,easy,interesting,is,learn,learning,love,nlp,programming,python,to,useful
0,0,0,0,0,0,0,1,0,1,1,0,0
1,0,1,0,1,1,0,0,0,0,1,1,0
2,0,0,0,0,0,1,1,1,0,0,0,0
3,1,0,1,1,0,0,0,1,0,0,0,1

In [14]:
binary_vectorizer = CountVectorizer(binary=True)

binary_matrix = binary_vectorizer.fit_transform(documents)

print(binary_matrix.toarray())

[[0 0 0 0 0 0 1 0 1 1 0 0]
 [0 1 0 1 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0]
 [1 0 1 1 0 0 0 1 0 0 0 1]]

In [15]:
unigram_vectorizer = CountVectorizer(
    ngram_range=(1, 1)
)

unigram_vectorizer.fit(documents)

print(unigram_vectorizer.get_feature_names_out())

['and' 'easy' 'interesting' 'is' 'learn' 'learning' 'love' 'nlp'
 'programming' 'python' 'to' 'useful']

In [16]:
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2)
)

bigram_vectorizer.fit(documents)

print(bigram_vectorizer.get_feature_names_out())

['and useful' 'easy to' 'interesting and' 'is easy' 'is interesting'
 'learning nlp' 'love learning' 'love python' 'nlp is' 'python is'
 'python programming' 'to learn']

In [17]:
trigram_vectorizer = CountVectorizer(
    ngram_range=(3, 3)
)

trigram_vectorizer.fit(documents)

print(trigram_vectorizer.get_feature_names_out())

['easy to learn' 'interesting and useful' 'is easy to'
 'is interesting and' 'love learning nlp' 'love python programming'
 'nlp is interesting' 'python is easy']

In [18]:
tfidf_vectorizer = TfidfVectorizer()

In [19]:
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

In [20]:
tfidf_vocabulary = tfidf_vectorizer.get_feature_names_out()

print(tfidf_vocabulary)

['and' 'easy' 'interesting' 'is' 'learn' 'learning' 'love' 'nlp'
 'programming' 'python' 'to' 'useful']

In [21]:
print(tfidf_matrix.toarray())

[[0.         0.         0.         0.         0.         0.
  0.52640543 0.         0.66767854 0.52640543 0.         0.        ]
 [0.         0.48546061 0.         0.38274272 0.48546061 0.
  0.         0.         0.         0.38274272 0.48546061 0.        ]
 [0.         0.         0.         0.         0.         0.66767854
  0.52640543 0.52640543 0.         0.         0.         0.        ]
 [0.48546061 0.         0.48546061 0.38274272 0.         0.
  0.         0.38274272 0.         0.         0.         0.48546061]]

In [22]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vocabulary
)

tfidf_df.round(3)

,and,easy,interesting,is,learn,learning,love,nlp,programming,python,to,useful
0,0.000,0.000,0.000,0.000,0.000,0.000,0.526,0.000,0.668,0.526,0.000,0.000
1,0.000,0.485,0.000,0.383,0.485,0.000,0.000,0.000,0.000,0.383,0.485,0.000
2,0.000,0.000,0.000,0.000,0.000,0.668,0.526,0.526,0.000,0.000,0.000,0.000
3,0.485,0.000,0.485,0.383,0.000,0.000,0.000,0.383,0.000,0.000,0.000,0.485

In [23]:
sentences = [
    ["i", "love", "python", "programming"],
    ["python", "is", "easy", "to", "learn"],
    ["i", "love", "learning", "nlp"],
    ["nlp", "is", "interesting", "and", "useful"],
    ["python", "is", "powerful"],
    ["nlp", "is", "useful"],
    ["i", "enjoy", "python"],
    ["i", "enjoy", "nlp"]
]

for sentence in sentences:
    print(sentence)

['i', 'love', 'python', 'programming']
['python', 'is', 'easy', 'to', 'learn']
['i', 'love', 'learning', 'nlp']
['nlp', 'is', 'interesting', 'and', 'useful']
['python', 'is', 'powerful']
['nlp', 'is', 'useful']
['i', 'enjoy', 'python']
['i', 'enjoy', 'nlp']

In [24]:
cbow_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=3,
    min_count=1,
    sg=0,
    workers=1,
    seed=42
)

In [25]:
python_vector = cbow_model.wv["python"]

print(python_vector)

[-2.6717109e-03  8.1691220e-03 -9.6214928e-05  3.9899349e-03
 -8.4938796e-04 -4.6804817e-03  5.2870507e-03  9.3855262e-03
 -4.7302675e-03  5.5767680e-03 -4.7794948e-03  4.3404410e-03
  5.7804915e-03 -1.0129267e-03  4.7384184e-03 -4.5545399e-03
 -8.4190145e-03 -8.0754319e-03 -1.0613563e-03  8.0489945e-03
 -7.4486742e-03 -8.8263140e-04  4.0822164e-03 -5.9530530e-03
  4.4351225e-03 -3.8800030e-03  6.1697871e-03  1.5871769e-03
  9.3849504e-04 -6.4633787e-03 -7.3527498e-04  7.1326797e-03
 -9.6133221e-03  5.1710312e-03 -1.4238044e-04  4.3872762e-03
  3.2666875e-03 -1.3620504e-03 -3.8282995e-03  2.5459433e-03
 -7.1914466e-03  1.6797750e-03 -8.1076799e-03  2.9961502e-03
  2.5790429e-03 -8.3086882e-03  5.1462739e-03 -1.6858776e-03
  5.7406416e-03 -9.1718752e-03 -6.4081233e-03 -1.2235400e-04
 -6.2325569e-03 -3.4048373e-03  3.2116768e-03 -7.1087466e-03
  3.5513339e-03 -7.9315938e-03 -6.4964667e-03  1.7554542e-03
  5.8742487e-03 -6.5868353e-03 -4.0013241e-03  8.5016582e-03
  9.7933989e-03  1.6236581e-03 -1.0607110e-03 -3.0655852e-03
  2.2478669e-03  1.8138514e-03 -4.1082120e-03 -9.5475316e-03
 -6.9678319e-03  9.1731502e-03 -1.6349587e-03 -3.5446757e-04
 -6.5611961e-04  5.6519257e-03 -8.6980155e-03 -8.3455602e-03
 -4.4797994e-03 -2.7003133e-04  3.4223972e-03 -1.8451903e-04
 -1.1767619e-03  8.7565212e-03 -6.7827469e-03  1.4332111e-03
  8.4222719e-04 -5.3195149e-04  6.1534750e-03 -4.6594231e-03
  9.0761175e-03 -3.3701835e-03  9.0410555e-04  4.0990775e-04
  6.9943424e-03 -1.2248345e-03 -4.3101874e-03 -9.5639257e-03]

In [26]:
print(python_vector.shape)

(100,)

In [27]:
similar_words = cbow_model.wv.most_similar(
    "python",
    topn=5
)

print(similar_words)

[('and', 0.16586986184120178), ('i', 0.10434465855360031), ('easy', 0.09607067704200745), ('learning', 0.06667351722717285), ('powerful', 0.06300230324268341)]

In [28]:
skipgram_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=3,
    min_count=1,
    sg=1,
    workers=1,
    seed=42
)

In [29]:
nlp_vector = skipgram_model.wv["nlp"]

print(nlp_vector)

[-8.2149813e-03  5.4791202e-03  3.0914294e-03 -1.2224317e-03
 -1.3396954e-03  7.1719573e-03 -8.2810875e-03  3.9473604e-03
 -5.9706103e-03 -8.1164539e-03  5.2957895e-04  9.5124459e-03
  4.7150468e-03  5.2227937e-03  4.3495451e-03  5.7212855e-03
  2.6453138e-04 -7.4377274e-03  6.7949640e-03 -9.9228148e-04
  7.0381166e-06 -2.5840402e-03 -6.3490081e-03  8.5352995e-03
  5.6313490e-03  2.8773022e-03 -1.9517136e-03  6.4552319e-03
  9.0858224e-04 -1.1317170e-03 -9.9080917e-04 -5.4552257e-03
 -8.1572821e-03  1.0916948e-03  7.7577960e-03 -8.7236557e-03
  7.1658255e-03  6.5526222e-03 -4.4648065e-03  2.6332878e-03
 -6.6954195e-03  5.1617539e-03  4.0104594e-03 -2.9094815e-03
 -8.6416006e-03  9.4139604e-03 -1.0862505e-03  7.8624217e-03
  3.5583794e-03  5.5676699e-03  5.1979888e-03 -6.1072265e-03
 -2.7218794e-03 -6.6558004e-04 -4.4169425e-05 -9.1239251e-03
  9.3138934e-04 -6.9142105e-03  4.8675179e-03  3.6609781e-03
  8.4505556e-03  4.8952424e-03 -2.6671470e-03  9.3501937e-03
 -1.7829931e-03 -3.4834933e-03  8.1107151e-03 -2.5908065e-03
 -8.4731365e-03 -6.0888409e-04  5.9135985e-03 -6.2105739e-03
 -7.4118969e-04 -7.4015702e-03  3.7295639e-03 -4.8590184e-04
 -3.3960736e-03 -5.4618134e-03  1.2899971e-03  3.3962799e-03
  8.8061215e-03 -1.2569618e-03 -6.7862365e-03  6.6535627e-03
  2.5952852e-03  4.0053008e-03 -8.0554672e-03 -3.7526679e-03
  5.3568780e-03  6.6451957e-03 -1.2956667e-03  6.0952865e-03
  6.8338369e-03 -2.2504330e-03  7.9617528e-03 -4.2334390e-03
 -5.2088453e-03  3.6499095e-03  2.7352357e-03 -7.2049513e-03]

In [30]:
print(nlp_vector.shape)

(100,)

In [31]:
similarity = skipgram_model.wv.similarity(
    "python",
    "programming"
)

print(similarity)

0.043906953

In [32]:
fasttext_model = FastText(
    sentences=sentences,
    vector_size=100,
    window=3,
    min_count=1,
    workers=1,
    seed=42
)

In [33]:
fasttext_vector = fasttext_model.wv["python"]

print(fasttext_vector)

[ 1.33503263e-03 -6.12586446e-04  1.52373943e-03  6.99330994e-04
  1.78752438e-04  1.03258912e-03 -1.18123146e-03  1.89374841e-04
  1.06955494e-03 -4.25379229e-04 -3.26175417e-04 -5.84173657e-04
 -1.33102736e-03  3.02837486e-03 -6.01213833e-05 -1.50185672e-03
 -1.71112292e-03 -1.27948809e-03 -1.27452728e-03  2.95786740e-04
 -2.06957012e-03  4.06795676e-04  8.35514220e-05 -2.45252694e-03
 -1.42783078e-03 -2.57202744e-04  1.57201255e-03 -7.34206231e-04
  9.31170012e-04 -5.46603755e-04 -1.70638447e-03  1.68145297e-03
 -8.92150056e-05 -2.74536840e-04  1.30867341e-03  1.68744847e-03
  1.99834234e-03  1.76114764e-03 -5.47144387e-04  5.83237445e-04
 -7.44765159e-04 -2.38735392e-03 -2.16018362e-03 -2.26399625e-05
  5.49179036e-04 -4.05203842e-04  2.18077097e-03 -5.15953114e-04
  8.11701058e-04 -1.61841139e-03 -1.72033775e-04  3.88479559e-04
 -1.25571198e-04 -1.00536126e-04 -2.51277204e-04 -8.58089246e-04
 -3.34873213e-04  7.67697580e-04 -5.71249635e-04  1.82462914e-03
  3.06977145e-03 -1.20382733e-03 -4.58130671e-04  7.33629568e-04
  6.66509033e-04  1.82264776e-04 -1.12000993e-03  7.75780471e-04
 -1.05377380e-03  6.54410978e-05  3.94788454e-04 -3.08215548e-03
 -5.97259670e-04 -1.00932189e-03 -1.51543805e-04 -8.87072179e-04
  2.57183239e-03  2.73316209e-06  1.07328626e-04  5.78047911e-05
  1.12129492e-03  1.49117928e-04  1.48796197e-03  1.86540780e-03
  2.98836912e-05  8.59809748e-04 -2.50629499e-04 -1.06017711e-03
  1.12486632e-04 -5.56927058e-04  3.82512412e-03  7.90508755e-04
 -4.42720368e-04  4.75827910e-05  8.18395230e-04  1.09756330e-03
  1.41690555e-03 -2.08212878e-03 -1.32160739e-03 -6.27084519e-05]

In [34]:
print(fasttext_vector.shape)

(100,)

In [35]:
fasttext_similar = fasttext_model.wv.most_similar(
    "python",
    topn=5
)

print(fasttext_similar)

[('i', 0.10799195617437363), ('easy', 0.10178328305482864), ('and', 0.07938851416110992), ('is', 0.0747564509510994), ('useful', 0.050724998116493225)]

In [36]:
new_word = "pythonprogramming"

vector = fasttext_model.wv[new_word]

print(vector)

[-9.5623836e-04 -2.3260301e-04  3.6529903e-04 -4.0347292e-04
 -3.2723395e-04 -1.5773841e-03 -5.9239708e-05 -7.5666944e-04
 -8.0426678e-04 -3.8593714e-04  3.0367539e-04  1.1620075e-03
  4.3225277e-04 -9.7343422e-05  3.3442862e-04  1.2925013e-04
 -2.6697351e-04 -6.4078980e-04  4.1795670e-04 -1.2416359e-04
 -1.3829309e-03 -5.8119249e-04 -8.0723531e-04 -1.1061132e-03
 -5.0309260e-04  1.3238991e-04  1.7556644e-04 -5.1276555e-04
  1.2911155e-04  8.6163759e-04 -1.2493517e-03 -7.6425640e-05
 -4.3557491e-05  1.6966487e-04  3.4719819e-04  2.5545366e-04
  9.0619060e-04  5.3240731e-04  1.4082508e-04 -4.8157418e-04
  4.6827682e-04 -8.3767332e-04 -4.1900258e-04  3.5142693e-05
  9.3741657e-04 -2.2090660e-04  9.2116022e-04  5.1735678e-05
  4.8408358e-04 -5.7458674e-04  3.6410656e-04  3.6862996e-04
 -5.0111074e-04  7.0115330e-04  1.8024698e-04 -7.2429091e-04
 -2.8856311e-04  5.9340480e-05  2.2409013e-03  2.1301223e-04
  8.8692771e-04  1.0344854e-03 -4.9263681e-04 -1.2990854e-03
  1.3269099e-03 -6.6168932e-04 -8.3145802e-04  1.8682434e-04
 -1.6580625e-04 -4.4100283e-04  1.7993191e-04 -7.4286445e-04
 -4.7139448e-04 -1.4152523e-04  6.8003969e-04 -1.0088610e-03
 -2.4129300e-04 -6.5949105e-04  2.7974418e-04 -6.8835070e-04
  6.5942481e-04  1.3065634e-03  3.1139684e-04  4.7169084e-04
 -2.3717250e-04 -4.8026390e-04 -7.1930874e-04  5.1566242e-04
 -2.1103790e-04 -3.8015275e-04  8.3786761e-04  8.3349284e-04
 -9.3146722e-04  9.4332383e-04  1.2082516e-05  8.1077212e-04
 -2.8018572e-04  3.0613117e-04 -6.5287395e-04 -6.6609442e-04]

In [37]:
python_vector = skipgram_model.wv["python"]
nlp_vector = skipgram_model.wv["nlp"]

similarity = cosine_similarity(
    [python_vector],
    [nlp_vector]
)

print(similarity)

[[0.02707248]]

In [38]:
sentence1 = ["I love Python programming"]

sentence2 = ["Python programming is interesting"]

combined_sentences = sentence1 + sentence2

vectorizer = TfidfVectorizer()

vectors = vectorizer.fit_transform(combined_sentences)

print(vectors.toarray())

[[0.         0.         0.70490949 0.50154891 0.50154891]
 [0.57615236 0.57615236 0.         0.40993715 0.40993715]]

In [39]:
similarity = cosine_similarity(vectors)

print(similarity)

[[1.         0.41120706]
 [0.41120706 1.        ]]